server:
  ssl:
    key-store: classpath:springboot.jks
    key-store-password: password
    key-store-type: jks
    key-alias: springboot
    key-password: password
  port: 8443
  
  
  
local:
  development:
    port: 8099